name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.5.1 [CE|EE|ECE 2.4.0-2.4.7] 18 May 2024
          tag_name: 1.5.1
          body: |-
            ### softcommerce/module-core [1.5.1]
            - **Feature**: Added service & processor interface wrapper for dependant modules that use data processing.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
